### ISSUE TITLE
Create models, urls and views for a student to upload his/her work. Check description for more details.

### ISSUE THREAD

**Issue by danielsumah** [zuri-training/MyInternApp-be-pjt-38#49]
The models that will be created should follow the format in the UI design below
![upload work student](https://user-images.githubusercontent.com/52764894/124276801-2f1ecb00-db3c-11eb-9620-b04c1290fb7f.png)
Please note that for every attribute of the model are compulsory for a student to save.

**Comment by JbOsunlana** [comment]
Acknowledged
